Repository Team-Shaka/Briefing-Backend, pull requests merged in 2023-12, with the labels that each got.

#93 Feature/90 : 브리핑 목록 조회 v2 수정사항
  src/main/java/briefing/briefing/api/BriefingConverter.java
  src/main/java/briefing/briefing/application/BriefingQueryService.java
  src/main/java/briefing/briefing/application/dto/BriefingRequestParam.java
  src/main/java/briefing/briefing/application/strategy/BriefingV2QueryStrategy.java
  src/main/java/briefing/briefing/domain/BriefingType.java
  src/main/java/briefing/briefing/domain/repository/BriefingCustomRepository.java
  src/main/java/briefing/briefing/domain/repository/BriefingCustomRepositoryImpl.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#95 ✨ Feat: 브리핑 단건 조회 v2 수정사항
  src/main/java/briefing/briefing/api/BriefingConverter.java
  src/main/java/briefing/briefing/application/dto/BriefingResponseDTO.java
Labels: :sparkles: feature

#98 ✨ Feat: 스크랩 목록 조회 응답 필드 추가
  src/main/java/briefing/scrap/api/ScrapConverter.java
  src/main/java/briefing/scrap/application/dto/ScrapResponse.java
Labels: :sparkles: feature

#103 Feature/102 : API URI 버저닝
  src/main/java/briefing/briefing/api/BriefingApi.java
  src/main/java/briefing/briefing/api/BriefingConverter.java
  src/main/java/briefing/briefing/application/dto/BriefingRequestParam.java
  src/main/java/briefing/briefing/application/dto/BriefingResponseDTO.java
  src/main/java/briefing/member/api/MemberApi.java
  src/main/java/briefing/scrap/api/ScrapApi.java
  src/main/java/briefing/scrap/api/ScrapConverter.java
  src/main/java/briefing/scrap/application/dto/ScrapResponse.java
  src/main/java/briefing/security/config/SecurityConfig.java
Labels: :sparkles: feature

#105 issue/104 🐛 Fix : redis 연결정보 환경변수로 변경
  src/main/resources/application.yml
Labels: :bug: bug

#106 issue/104 🐛 Fix : application.yml dev 프로필 설정 수정
  src/main/resources/application.yml
Labels: :bug: bug

#107 issue/104 🐛 Fix : eureka 접속정보 수정
  src/main/resources/application.yml
Labels: :bug: bug

#108 Feature/96: 스크랩 동시성 이슈 방지하기
  src/main/java/briefing/exception/ErrorCode.java
  src/main/java/briefing/scrap/application/ScrapCommandService.java
  src/main/java/briefing/scrap/domain/Scrap.java
Labels: :sparkles: feature

#109 issue/104 Fix : eureka 설정 정보 수정
  src/main/resources/application.yml
Labels: :bug: bug

#110 Fix : eureka server에 등록될 이름 수정
  src/main/resources/application.yml
Labels: :bug: bug

#111 ✨ Feat: 브리핑 목록 조회 v1 쿼리 전략 변경
  src/main/java/briefing/briefing/application/BriefingQueryService.java
  src/main/java/briefing/briefing/application/strategy/BriefingV1QueryStrategy.java
Labels: :sparkles: feature

#114 👷 Ci: 스크립트 변경
  .github/workflows/dev_deploy.yml
  .github/workflows/release_deploy.yml
Labels: :construction_worker: ci

#116 👷 Ci: 스크립트 변경
  .github/workflows/dev_deploy.yml
  .github/workflows/release_deploy.yml
Labels: :construction_worker: ci

#117 👷 Ci: push 트리거 제거
  .github/workflows/dev_deploy.yml
  .github/workflows/release_deploy.yml
Labels: :construction_worker: ci

#119 Briefing 2.0.0 서버 업데이트
  .github/workflows/dev_deploy.yml
  .github/workflows/release_deploy.yml
  README.md
  build.gradle
  gradlew
  src/main/generated/briefing/base/QBaseDateTimeEntity.java
  src/main/generated/briefing/briefing/domain/QArticle.java
  src/main/generated/briefing/briefing/domain/QBriefing.java
  src/main/generated/briefing/briefing/domain/QBriefingArticle.java
  src/main/generated/briefing/chatting/domain/QChatting.java
  src/main/generated/briefing/chatting/domain/QMessage.java
  src/main/generated/briefing/member/domain/QMember.java
  src/main/generated/briefing/scrap/domain/QScrap.java
  src/main/java/briefing/briefing/api/BriefingApi.java
  src/main/java/briefing/briefing/api/BriefingConverter.java
  src/main/java/briefing/briefing/application/BriefingQueryService.java
  src/main/java/briefing/briefing/application/context/BriefingQueryContext.java
  src/main/java/briefing/briefing/application/context/BriefingQueryContextFactory.java
  src/main/java/briefing/briefing/application/dto/BriefingRequestDTO.java
  src/main/java/briefing/briefing/application/dto/BriefingRequestParam.java
  src/main/java/briefing/briefing/application/dto/BriefingResponseDTO.java
  src/main/java/briefing/briefing/application/strategy/BriefingQueryStrategy.java
  src/main/java/briefing/briefing/application/strategy/BriefingV1QueryStrategy.java
  src/main/java/briefing/briefing/application/strategy/BriefingV2QueryStrategy.java
  src/main/java/briefing/briefing/domain/Briefing.java
  src/main/java/briefing/briefing/domain/BriefingType.java
  src/main/java/briefing/briefing/domain/TimeOfDay.java
  src/main/java/briefing/briefing/domain/repository/BriefingCustomRepository.java
  src/main/java/briefing/briefing/domain/repository/BriefingCustomRepositoryImpl.java
  src/main/java/briefing/briefing/domain/repository/BriefingRepository.java
  src/main/java/briefing/chatting/domain/GptModel.java
  src/main/java/briefing/common/enums/APIVersion.java
  src/main/java/briefing/config/GlobalWebConfig.java
  src/main/java/briefing/config/QueryDslConfig.java
  src/main/java/briefing/converter/APIVersionRequestConverter.java
  src/main/java/briefing/converter/TimeOfDayConverter.java
  src/main/java/briefing/exception/ErrorCode.java
  src/main/java/briefing/member/api/MemberApi.java
  src/main/java/briefing/member/domain/Member.java
  src/main/java/briefing/scrap/api/ScrapApi.java
  src/main/java/briefing/scrap/api/ScrapConverter.java
  src/main/java/briefing/scrap/application/ScrapCommandService.java
  src/main/java/briefing/scrap/application/dto/ScrapResponse.java
  src/main/java/briefing/scrap/domain/Scrap.java
  src/main/java/briefing/security/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: :construction_worker: ci

#121 🐛 Fix: 역순 정렬 v1 브리핑 목록 조회
  src/main/java/briefing/briefing/application/strategy/BriefingV1QueryStrategy.java
Labels: :bug: bug

#122 Briefing v1 목록 조회 버그 반영
  src/main/java/briefing/briefing/application/strategy/BriefingV1QueryStrategy.java
Labels: :bug: bug

#124 ♻️ Refactor: OCP를 준수하는 방향으로 전략 패턴 코드 리팩토링
  src/main/java/briefing/briefing/application/BriefingQueryService.java
  src/main/java/briefing/briefing/application/context/BriefingQueryContextFactory.java
  src/main/java/briefing/briefing/application/strategy/BriefingQueryStrategy.java
  src/main/java/briefing/briefing/application/strategy/BriefingV1QueryStrategy.java
  src/main/java/briefing/briefing/application/strategy/BriefingV2QueryStrategy.java
Labels: :recycle: refactor

#128 ✨ Feat: 브리핑 목록 조회 V2 방어적 작성
  src/main/java/briefing/briefing/application/strategy/BriefingV2QueryStrategy.java
Labels: :sparkles: feature

#129 ✨ Feat: 브리핑 목록 조회 V2 방어적 작성
  README.md
  src/main/java/briefing/briefing/application/BriefingQueryService.java
  src/main/java/briefing/briefing/application/context/BriefingQueryContextFactory.java
  src/main/java/briefing/briefing/application/strategy/BriefingQueryStrategy.java
  src/main/java/briefing/briefing/application/strategy/BriefingV1QueryStrategy.java
  src/main/java/briefing/briefing/application/strategy/BriefingV2QueryStrategy.java
Labels: :sparkles: feature

#132 💚 Ci : 서버 이전으로 인한 github action 수정
  .github/workflows/dev_deploy.yml
  src/main/java/briefing/exception/common/ApiErrorResult.java
  src/main/java/briefing/security/config/SecurityConfig.java
Labels: :construction_worker: ci
