Repository Team-Shaka/Briefing-Backend, pull requests merged in 2023-09, with the labels that each got.

#5 ci test
  briefing/logs/info.log
  briefing/src/main/java/briefing/root/api/RootApi.java
Labels: :bug: bug

#7 👷[CI] Ci : nginx 설정 추가
  .platform/nginx.conf
Labels: :sparkles: feature

#12 Issue/11: 이슈 & PR 템플릿
  .github/ISSUE_TEMPLATE/🐛-bug-.md
  .github/ISSUE_TEMPLATE/📝-docs-.md
  .github/ISSUE_TEMPLATE/🔨-refactor-.md
  .github/ISSUE_TEMPLATE/🚀--feature-.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: :sparkles: feature

#20 Feature/15: 소셜로그인 코드베이스
  logs/info.log
  src/main/java/briefing/common/response/CommonResponse.java
  src/main/java/briefing/common/response/PageResponse.java
  src/main/java/briefing/config/GlobalWebConfig.java
  src/main/java/briefing/converter/SocialTypeRequestConverter.java
  src/main/java/briefing/member/api/MemberApi.java
  src/main/java/briefing/member/api/MemberConverter.java
  src/main/java/briefing/member/application/MemberCommandService.java
  src/main/java/briefing/member/application/MemberQueryService.java
  src/main/java/briefing/member/application/dto/MemberRequest.java
  src/main/java/briefing/member/application/dto/MemberResponse.java
  src/main/java/briefing/member/domain/Member.java
  src/main/java/briefing/member/domain/MemberRole.java
  src/main/java/briefing/member/domain/MemberStatus.java
  src/main/java/briefing/member/domain/SocialType.java
  src/main/java/briefing/member/domain/repository/MemberRepository.java
Labels: :sparkles: feature

#18 Docs/16 📋 [docs] swagger 세팅
  .ebextension/00-makeFiles.config
  build.gradle
  logs/info.log
  src/main/java/briefing/config/SwaggerConfig.java
Labels: :memo: documentation

#22 issue/21 ✨ Feat : spring security 설정 추가
  build.gradle
  logs/info.2023-09-16.log
  logs/info.log
  src/main/java/briefing/exception/ErrorCode.java
  src/main/java/briefing/exception/GeneralException.java
  src/main/java/briefing/exception/common/ApiErrorResult.java
  src/main/java/briefing/exception/handler/JwtAuthenticationException.java
  src/main/java/briefing/security/config/JwtSecurityConfig.java
  src/main/java/briefing/security/config/SecurityConfig.java
  src/main/java/briefing/security/filter/JwtRequestFilter.java
  src/main/java/briefing/security/handler/JwtAccessDeniedHandler.java
  src/main/java/briefing/security/handler/JwtAuthenticationEntryPoint.java
  src/main/java/briefing/security/handler/JwtAuthenticationExceptionHandler.java
  src/main/java/briefing/security/provider/TokenProvider.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#25 issue/23 🚀 [feature] FeignClient 세팅
  .gitignore
  build.gradle
  src/main/java/briefing/BriefingApplication.java
  src/main/java/briefing/GlobalControllerAdvice.java
  src/main/java/briefing/exception/ErrorCode.java
  src/main/java/briefing/exception/ExceptionHandler.java
  src/main/java/briefing/exception/handler/CustomFeignClientException.java
  src/main/java/briefing/feign/exception/FeignClientExceptionErrorDecoder.java
Labels: :sparkles: feature

#26 Fix: Build error
  logs/info.log
  src/main/java/briefing/exception/ErrorCode.java
Labels: :bug: bug

#28 ✨ Feat: 구글 로그인 구현
  build.gradle
  logs/info.log
  src/main/java/briefing/BriefingApplication.java
  src/main/java/briefing/feign/oauth/google/client/GoogleOauth2Client.java
  src/main/java/briefing/feign/oauth/google/config/GoogleOauth2FeignConfiguration.java
  src/main/java/briefing/feign/oauth/google/dto/GoogleUserInfo.java
  src/main/java/briefing/member/api/MemberConverter.java
  src/main/java/briefing/member/application/MemberCommandService.java
  src/main/java/briefing/member/domain/Member.java
  src/main/java/briefing/member/domain/repository/MemberRepository.java
  src/main/java/briefing/security/config/SecurityConfig.java
Labels: :sparkles: feature

#29 Feature/23 🚀 [feature] Apple 소셜로그인 구현
  .gitignore
  build.gradle
  logs/info.log
  src/main/java/briefing/exception/handler/AppleOAuthException.java
  src/main/java/briefing/feign/oauth/apple/client/AppleOauth2Client.java
  src/main/java/briefing/feign/oauth/apple/config/AppleOauth2FeignConfiguration.java
  src/main/java/briefing/feign/oauth/apple/dto/ApplePublicKey.java
  src/main/java/briefing/feign/oauth/apple/dto/ApplePublicKeyList.java
  src/main/java/briefing/member/api/MemberConverter.java
  src/main/java/briefing/member/application/MemberCommandService.java
Labels: :sparkles: feature

#31 📝 Docs: 스웨거 작성
  logs/error.log
  logs/info.log
  src/main/java/briefing/briefing/api/BriefingApi.java
  src/main/java/briefing/chatting/api/ChattingApi.java
  src/main/java/briefing/member/api/MemberApi.java
  src/main/java/briefing/member/domain/SocialType.java
  src/main/java/briefing/root/api/RootApi.java
  src/main/resources/application.yml
Labels: :memo: documentation

#34 issue/32 ♻️ Refactor : API 응답 통일
  logs/info.log
  src/main/java/briefing/briefing/api/BriefingApi.java
  src/main/java/briefing/chatting/api/ChattingApi.java
Labels: :recycle: refactor

#36 Feature/33 : 스크랩 기능
  logs/info.2023-09-16.log
  logs/info.log
  src/main/java/briefing/exception/ErrorCode.java
  src/main/java/briefing/member/domain/Member.java
  src/main/java/briefing/member/exception/MemberException.java
  src/main/java/briefing/scrap/api/ScrapApi.java
  src/main/java/briefing/scrap/api/ScrapConverter.java
  src/main/java/briefing/scrap/application/ScrapCommandService.java
  src/main/java/briefing/scrap/application/ScrapQueryService.java
  src/main/java/briefing/scrap/application/dto/ScrapRequest.java
  src/main/java/briefing/scrap/application/dto/ScrapResponse.java
  src/main/java/briefing/scrap/domain/Scrap.java
  src/main/java/briefing/scrap/domain/repository/ScrapRepository.java
  src/main/java/briefing/scrap/exception/ScrapException.java
  src/main/java/briefing/security/config/SecurityConfig.java
Labels: :sparkles: feature

#35 Feature/19 🚀 [feature] redis 설정 및 리프레쉬 토큰 관리 추가
  build.gradle
  logs/info.log
  src/main/java/briefing/exception/ErrorCode.java
  src/main/java/briefing/exception/handler/MemberException.java
  src/main/java/briefing/exception/handler/RefreshTokenException.java
  src/main/java/briefing/member/api/MemberApi.java
  src/main/java/briefing/member/application/MemberQueryService.java
  src/main/java/briefing/member/application/dto/MemberRequest.java
  src/main/java/briefing/redis/domain/RefreshToken.java
  src/main/java/briefing/redis/repository/RefreshTokenRepository.java
  src/main/java/briefing/redis/service/RedisService.java
  src/main/java/briefing/redis/service/RedisServiceImpl.java
  src/main/resources/application.yml
Labels: :sparkles: feature
