Repository Team-Shaka/Briefing-Backend, pull requests merged in 2023-10, with the labels that each got.

#40 issue/39 ♻️ Refactor : 토큰 발급 수정
  src/main/java/briefing/BriefingApplication.java
  src/main/java/briefing/member/api/MemberApi.java
  src/main/java/briefing/member/api/MemberConverter.java
  src/main/java/briefing/member/application/MemberCommandService.java
  src/main/java/briefing/member/application/MemberQueryService.java
  src/main/java/briefing/member/application/dto/MemberRequest.java
  src/main/java/briefing/member/application/dto/MemberResponse.java
  src/main/java/briefing/member/domain/repository/MemberRepository.java
  src/main/java/briefing/redis/service/RedisService.java
  src/main/java/briefing/redis/service/RedisServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: :bug: bug, :recycle: refactor

#42 Bug/39 redis 연결정보 수정
  src/main/resources/application.yml
Labels: :bug: bug

#44 Bug/39 redis 연결정보 수정
  src/main/resources/application.yml
Labels: :bug: bug

#49 ♻️ Refactor: scrap삭제 API
  src/main/java/briefing/scrap/api/ScrapApi.java
  src/main/java/briefing/scrap/application/ScrapCommandService.java
  src/main/java/briefing/scrap/domain/repository/ScrapRepository.java
Labels: :recycle: refactor

#51 💚 [Ci] : 서버시간 수정
  .ebextensions/01-set-timezone.config
Labels: :construction_worker: ci

#53 ✨ [Feat] : 회원탈퇴 API 구현
  src/main/java/briefing/config/GlobalWebConfig.java
  src/main/java/briefing/config/SwaggerConfig.java
  src/main/java/briefing/exception/ErrorCode.java
  src/main/java/briefing/member/api/MemberApi.java
  src/main/java/briefing/member/api/MemberConverter.java
  src/main/java/briefing/member/application/MemberCommandService.java
  src/main/java/briefing/member/application/MemberQueryService.java
  src/main/java/briefing/member/application/dto/MemberResponse.java
  src/main/java/briefing/member/domain/Member.java
  src/main/java/briefing/scrap/domain/Scrap.java
  src/main/java/briefing/security/handler/annotation/AuthMember.java
  src/main/java/briefing/security/handler/annotation/AuthUserArgumentResolver.java
  src/main/java/briefing/validation/annotation/CheckSameMember.java
  src/main/java/briefing/validation/validator/CheckSameMemberValidator.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#55 issue/54 ♻️ Refactor : 에러 핸들러 수정
  src/main/java/briefing/common/response/CommonResponse.java
  src/main/java/briefing/exception/ExceptionAdvice.java
  src/main/java/briefing/exception/ExceptionHandler.java
  src/main/java/briefing/security/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: :recycle: refactor

#57 issue/56 🐛 Fix : redis 연결정보 수정
  src/main/resources/application.yml
Labels: :bug: bug

#59 issue/58 💚 [Ci] : 개발 인프라 도쿄로 이전
  .github/workflows/dev_deploy.yml
Labels: :construction_worker: ci

#63 💚 Ci : 릴리즈 인프라 구축
  .github/workflows/release_deploy.yml
Labels: :construction_worker: ci

#65 issue/60 💚 CI : 릴리즈 인프라 구축 (#64)
  .github/workflows/release_deploy.yml
Labels: :construction_worker: ci

#66 issue/60 🐛 FIX : release_deploy.yml 수정
  .github/workflows/release_deploy.yml
Labels: :bug: bug

#67 👷 CI : 릴리즈 인프라 구축
  .github/workflows/release_deploy.yml
Labels: :construction_worker: ci

#69 💚 Ci : 개발 인프라 이전
  .ebextensions-dev/00-makeFiles.config
  .ebextensions-dev/01-set-timezone.config
  .github/workflows/dev_deploy.yml
  src/main/resources/application.yml
Labels: :construction_worker: ci

#70 Ci/68 🐛 [FIX] application.yml profile 수정
  src/main/resources/application.yml
Labels: :bug: bug

#72 💚 Ci : release 인프라 application.yml profile 분리
  .ebextensions-release/00-makeFiles.config
  .ebextensions-release/01-set-timezone.config
  .github/workflows/release_deploy.yml
  src/main/resources/application.yml
Labels: :construction_worker: ci

#73 🚀 2023 10 13 release 릴리즈 인프라 application.yml profile 분리
  .ebextensions-dev/00-makeFiles.config
  .ebextensions-dev/01-set-timezone.config
  .ebextensions-release/00-makeFiles.config
  .ebextensions-release/01-set-timezone.config
  .github/workflows/dev_deploy.yml
  .github/workflows/release_deploy.yml
  src/main/resources/application.yml
Labels: :construction_worker: ci

#76 issue/75 🐛 Fix : accessToken 재발급 버그 수정
  src/main/java/briefing/exception/ErrorCode.java
  src/main/java/briefing/member/api/MemberApi.java
  src/main/java/briefing/member/api/MemberConverter.java
  src/main/java/briefing/member/application/dto/MemberResponse.java
  src/main/java/briefing/redis/domain/RefreshToken.java
  src/main/java/briefing/redis/repository/RefreshTokenRepository.java
  src/main/java/briefing/redis/service/RedisServiceImpl.java
Labels: :bug: bug

#77 Feature/74: isScrap 필드 추가
  src/main/java/briefing/briefing/api/BriefingApi.java
  src/main/java/briefing/briefing/api/BriefingConverter.java
  src/main/java/briefing/briefing/application/dto/BriefingResponseDTO.java
  src/main/java/briefing/member/api/MemberApi.java
  src/main/java/briefing/scrap/application/ScrapQueryService.java
  src/main/java/briefing/security/config/SecurityConfig.java
  src/main/java/briefing/security/filter/JwtRequestFilter.java
  src/main/java/briefing/security/handler/annotation/AuthUserArgumentResolver.java
Labels: :sparkles: feature

#79 ✨ Feat: isBrieifngOpen, isWarning 필드 추가
  src/main/java/briefing/briefing/api/BriefingApi.java
  src/main/java/briefing/briefing/api/BriefingConverter.java
  src/main/java/briefing/briefing/application/dto/BriefingResponseDTO.java
Labels: :sparkles: feature
