Repository Team-Shaka/Briefing-Backend, pull requests merged in 2024-07, with the labels that each got.

#210 :sparkles: Feat: API 응답 캐시 해제
  Briefing-Api/src/main/java/com/example/briefingapi/briefing/presentation/BriefingApi.java
  Briefing-Api/src/main/java/com/example/briefingapi/briefing/presentation/BriefingV2Api.java
  Briefing-Api/src/main/java/com/example/briefingapi/scrap/presentation/ScrapV2Api.java
Labels: :sparkles: feature

#212 Ci/211 : 운영 배포 스크립트 수정
  .github/workflows/release_deploy.yml
Labels: :construction_worker: ci

#214 Release 배포 0721
  Briefing-Api/src/main/java/com/example/briefingapi/briefing/implement/service/BriefingQueryAdapter.java
Labels: :construction_worker: ci

#215 Release 배포 0721
  .ebextensions-release/00-makeFiles.config
Labels: :construction_worker: ci

#216 :bug: Fix: flyway 버전 명시
  core/Briefing-Common/build.gradle
Labels: :bug: bug

#217 :pencil2: Fix: flyway 설정 파일 수정
  core/Briefing-Common/src/main/resources/application.yml
Labels: :bug: bug

#208 Feature/160 : 브리핑 목록 조회 쿼리 튜닝
  Briefing-Api/src/main/resources/application.yml
  core/Briefing-Common/src/main/java/com/example/briefingcommon/domain/repository/article/BriefingCustomRepositoryImpl.java
  core/Briefing-Common/src/main/resources/application.properties
  core/Briefing-Common/src/main/resources/application.yml
  src/main/resources/application.yml
Labels: :sparkles: feature
