Repository Team-Shaka/Briefing-Backend, pull requests merged in 2024-01, with the labels that each got.

#134 ♻️ Refactor : Swagger 로그인 및 리터칭
  src/main/java/briefing/BriefingApplication.java
  src/main/java/briefing/config/SwaggerConfig.java
  src/main/java/briefing/security/config/SecurityConfig.java
  src/main/java/briefing/security/handler/SwaggerLoginSuccessHandler.java
  src/main/resources/application.yml
Labels: :recycle: refactor

#142 ✨ Feat: API 응답 캐싱을 통한 브리핑 V2 조회 속도 개선
  src/main/java/briefing/BriefingApplication.java
  src/main/java/briefing/briefing/api/BriefingV2Api.java
  src/main/java/briefing/briefing/application/dto/BriefingRequestParam.java
  src/main/java/briefing/common/response/CommonResponse.java
  src/main/java/briefing/config/CacheConfig.java
  src/main/java/briefing/scrap/api/ScrapV2Api.java
Labels: :sparkles: feature

#143 ✏️ Fix: 캐시 키 변경 & 커스텀 캐시 Evict 로직 구현
  src/main/java/briefing/briefing/api/BriefingV2Api.java
  src/main/java/briefing/common/aop/annotation/CacheEvictByBriefingId.java
  src/main/java/briefing/common/aop/aspect/CacheEvictByBriefingIdAspect.java
  src/main/java/briefing/scrap/api/ScrapV2Api.java
Labels: :bug: bug, :sparkles: feature

#146 🐛 Fix: 브리핑 목록 조회 순위 버그 해결
  src/main/java/briefing/briefing/application/strategy/BriefingV1QueryStrategy.java
  src/main/java/briefing/briefing/application/strategy/BriefingV2QueryStrategy.java
  src/main/java/briefing/briefing/domain/repository/BriefingCustomRepositoryImpl.java
Labels: :bug: bug

#155 ♻️ Refactor: Chatting & Message 관련 코드 제거
  src/main/generated/briefing/briefing/domain/QBriefing.java
  src/main/generated/briefing/chatting/domain/QChatting.java
  src/main/generated/briefing/chatting/domain/QMessage.java
  src/main/java/briefing/briefing/application/dto/BriefingRequestDTO.java
  src/main/java/briefing/briefing/application/dto/BriefingResponseDTO.java
  src/main/java/briefing/briefing/domain/Briefing.java
  src/main/java/briefing/chatting/api/ChattingApi.java
  src/main/java/briefing/chatting/api/ChattingConverter.java
  src/main/java/briefing/chatting/application/ChatGptClient.java
  src/main/java/briefing/chatting/application/ChattingCommandService.java
  src/main/java/briefing/chatting/application/ChattingQueryService.java
  src/main/java/briefing/chatting/application/dto/ChattingRequest.java
  src/main/java/briefing/chatting/application/dto/ChattingResponse.java
  src/main/java/briefing/chatting/domain/Chatting.java
  src/main/java/briefing/chatting/domain/GptModel.java
  src/main/java/briefing/chatting/domain/Message.java
  src/main/java/briefing/chatting/domain/repository/ChattingRepository.java
  src/main/java/briefing/chatting/domain/repository/MessageRepository.java
  src/main/java/briefing/common/enums/GptModel.java
  src/main/java/briefing/config/GlobalWebConfig.java
  src/main/java/briefing/converter/GptModelRequestConverter.java
  src/main/java/briefing/converter/MessageRoleRequestConverter.java
  src/main/java/briefing/scrap/application/dto/ScrapResponse.java
  src/test/java/briefing/chatting/application/ChattingCommandServiceTest.java
Labels: :recycle: refactor

#153 ✨ Feat: 브리핑 목록 조회 V2 각 순위별 최신 브리핑 모아서 응답
  src/main/java/briefing/briefing/domain/repository/BriefingCustomRepositoryImpl.java
Labels: :sparkles: feature

#159 ✨ Feat: 캐시 무효화 정책 추가 (브리핑 등록, 수정 시)
  src/main/java/briefing/briefing/api/BriefingApi.java
Labels: :sparkles: feature

#162 Refactor/161 : Facade 도입 & 클래스 의존관계 개선
  src/main/java/briefing/briefing/api/BriefingApi.java
  src/main/java/briefing/briefing/api/BriefingV2Api.java
  src/main/java/briefing/briefing/application/BriefingCommandService.java
  src/main/java/briefing/briefing/application/BriefingFacade.java
  src/main/java/briefing/briefing/application/BriefingV2Facade.java
  src/main/java/briefing/briefing/application/service/ArticleCommandService.java
  src/main/java/briefing/briefing/application/service/BriefingArticleCommandService.java
  src/main/java/briefing/briefing/application/service/BriefingCommandService.java
  src/main/java/briefing/briefing/application/service/BriefingQueryService.java
  src/test/java/briefing/briefing/application/BriefingQueryServiceTest.java
Labels: :recycle: refactor
